In [30]:
import numpy as np
print(np.__version__)

1.14.2


# Joining array summary

In [31]:
a = np.zeros([3,3])
b = np.ones([3,3])
c0 = np.concatenate([a,b], axis=0)
c1 = np.concatenate([a,b], axis=1)
s0 = np.stack([a,b], axis=0)
s1 = np.stack([a,b], axis=1)
s2 = np.stack([a,b], axis=2)
ap0 = np.append(a,b, axis=0)
ap1 = np.append(a,b, axis=1)
ap = np.append(a,b)
print('concatenate shape: {} (axis=0)'.format(c0.shape))
print('concatenate shape: {} (axis=1)'.format(c1.shape))
print('stack shape: {} (axis=0)'.format(s0.shape))
print('stack shape: {} (axis=1)'.format(s1.shape))
print('stack shape: {} (axis=2)'.format(s2.shape))
print('append shape: {} (axis=0)'.format(ap0.shape))
print('append shape: {} (axis=1)'.format(ap1.shape))
print('append shape: {} (axis None)'.format(ap.shape))

concatenate shape: (6, 3) (axis=0)
concatenate shape: (3, 6) (axis=1)
stack shape: (2, 3, 3) (axis=0)
stack shape: (3, 2, 3) (axis=1)
stack shape: (3, 3, 2) (axis=2)
append shape: (6, 3) (axis=0)
append shape: (3, 6) (axis=1)
append shape: (18,) (axis None)


# Numpy axis 
## Rank 2 array
### The first index is axis 0 (row)

In [32]:
a = np.array(range(0,9)).reshape(3,3)
print('Array a:\n', a)
print('Index 0 of axis 0:', a[0])
print('Index 1 of axis 0:', a[1])
print('Index 2 of axis 0:', a[2])
print('Sum along axis 0 (row):', np.sum(a, axis=0))

Array a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Index 0 of axis 0: [0 1 2]
Index 1 of axis 0: [3 4 5]
Index 2 of axis 0: [6 7 8]
Sum along axis 0 (row): [ 9 12 15]


### The second index is axis 1 (column)

In [33]:
a = np.array(range(0,9)).reshape(3,3)
print('Array a:\n', a)
print('Index 0 of axis 1:', a[:,0])
print('Index 1 of axis 1:', a[:,1])
print('Index 2 of axis 1:', a[:,2])
print('Sum along axis 1 (column):', np.sum(a, axis=1))

Array a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Index 0 of axis 1: [0 3 6]
Index 1 of axis 1: [1 4 7]
Index 2 of axis 1: [2 5 8]
Sum along axis 1 (column): [ 3 12 21]


## Rank 3 array
Rank 3 array's axis definition is very similar to rank 2 array.

The most outer square brackets represents axis 0.

The most inner square brackets represents axis 2.

In [34]:
b = np.array(range(0,8)).reshape(2,2,2)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [35]:
print('Index 0 of axis 0:\n', b[0])
print('Index 1 of axis 0:\n', b[1])
print('Sum along axis 0:\n', np.sum(b, axis=0))

Index 0 of axis 0:
 [[0 1]
 [2 3]]
Index 1 of axis 0:
 [[4 5]
 [6 7]]
Sum along axis 0:
 [[ 4  6]
 [ 8 10]]


In [36]:
print('Index 0 of axis 1:\n', b[:,0,:])
print('Index 1 of axis 1:\n', b[:,1,:])
print('Sum along axis 1:\n', np.sum(b, axis=1))

Index 0 of axis 1:
 [[0 1]
 [4 5]]
Index 1 of axis 1:
 [[2 3]
 [6 7]]
Sum along axis 1:
 [[ 2  4]
 [10 12]]


In [37]:
print('Index 0 of axis 2:\n', b[:,:,0])
print('Index 1 of axis 2:\n', b[:,:,1])
print('Sum along axis 2:\n', np.sum(b, axis=2))

Index 0 of axis 2:
 [[0 2]
 [4 6]]
Index 1 of axis 2:
 [[1 3]
 [5 7]]
Sum along axis 2:
 [[ 1  5]
 [ 9 13]]


# np.concatenate
a is 3\*3 array. b is 1\*3 array.

c = np.concatenate([a,b], axis=0) 

c is 4\*3 array (3+1)\*3.

In [38]:
a = np.zeros([3,3])
b = np.ones([1,3])
c = np.concatenate([a,b], axis=0)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]]


In [39]:
a = np.zeros([3,3])
b = np.ones([3,5])
c = np.concatenate([a,b], axis=1)
print(c)

[[0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]]


# np.append
If axis is not specified, both arrays and values are flattened before use.

In [40]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.zeros([3,3])
b = np.ones([1,3])
c = np.append(a, b, axis=0)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]]


In [42]:
a = np.zeros([3,3])
b = np.ones([3,5])
c = np.append(a, b, axis=1)
print(c)

[[0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]]


# np.stack
Join a sequence of arrays along a new axis

In [43]:
a = np.zeros([3,3])
b = np.ones([3,3])
c = np.stack([a,b], axis=0)
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [44]:
a = np.zeros([3,3])
b = np.ones([3,3])
c = np.stack([a,b], axis=1)
print(c)

[[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]]


In [45]:
a = np.zeros([3,3])
b = np.ones([3,3])
c = np.stack([a,b], axis=2)
print(c)

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


[Numpy array manipulation][1]

[1]:https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html