# Pytorch basic 

In [149]:
import numpy as np
import torch as t
t.__version__

'0.4.0'

## Create tensor

In [148]:
x1 = t.empty(5,3, dtype=t.long)
print(x1) # empty tensor

tensor([[-2.3058e+18, -2.3058e+18,  8.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.3058e+18]])


In [19]:
x2 = t.ones(5,3)
print(x2)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [20]:
x3 = t.zeros(5,3)
print(x3)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [22]:
x4 = t.rand(5, 3)
print(x4) # a uniform distribution on the interval [0,1)

tensor([[ 0.9834,  0.5211,  0.0681],
        [ 0.0103,  0.8244,  0.6490],
        [ 0.5299,  0.0239,  0.1756],
        [ 0.5539,  0.3666,  0.7908],
        [ 0.8953,  0.4160,  0.1209]])


Construct tensor from list

In [150]:
x5 = t.tensor([[5.5, 3], [3, 0]])
print(x5)

tensor([[ 5.5000,  3.0000],
        [ 3.0000,  0.0000]])


Construct tensor from numpy array

In [155]:
arr = np.array([[5.5, 5], [3, 0]])
x6 = t.tensor(arr)
print(x6)

tensor([[ 5.5000,  5.0000],
        [ 3.0000,  0.0000]], dtype=torch.float64)


# Data type

Torch defines 8 different tensor types

https://pytorch.org/docs/stable/tensors.html#torch-tensor

Default data type are 
- float32 & int64 (from python list)
- float64 & int64 (from numpy ndarray)

Data type list
- t.float32 = t.float
- t.float64 = t.double
- t.float16 = t.halt
- t.uint8
- t.int8
- t.int16 = t.short
- t.int32 = t.int
- t.int64 = t.long

## From python list (int64 & float32)

In [156]:
x = t.tensor([1, 2, 3, 4])
print(x.dtype) # default int64 (long)

torch.int64


In [157]:
y = t.tensor([1.0, 2, 3, 4])
print(y.dtype) # default float32 (float)

torch.float32


## From numpy array (int64 & float64)

In [161]:
x = t.tensor(np.array([[1,2], [3,4]]))
print(x.dtype)

torch.int64


In [162]:
y = t.tensor(np.array([[1.0,2], [3,4]]))
print(y.dtype)

torch.float64


## Specific dtype

In [130]:
z = t.tensor([1, 2, 3, 4], dtype=t.float)
print(z.dtype)

torch.float32


In [131]:
z = t.tensor([1, 2, 3, 4], dtype=t.double)
print(z.dtype)

torch.float64


In [134]:
z = t.tensor([1, 2, 3, 4], dtype=t.half)
print(z.dtype)

torch.float16


In [136]:
z = t.tensor([1, 2, 3, 4], dtype=t.uint8)
print(z.dtype)

torch.uint8


In [137]:
z = t.tensor([1, 2, 3, 4], dtype=t.int8)
print(z.dtype)

torch.int8


In [138]:
z = t.tensor([1, 2, 3, 4], dtype=t.short)
print(z.dtype)

torch.int16


In [139]:
z = t.tensor([1, 2, 3, 4], dtype=t.int)
print(z.dtype)

torch.int32


In [140]:
z = t.tensor([1, 2, 3, 4], dtype=t.long)
print(z.dtype)

torch.int64


## Operations

### Add

In [100]:
x = t.tensor([[5.0, 3], [1, 0]], dtype=t.float)
y = t.tensor([[1.0, 0], [2, 4]], dtype=t.float)

In [101]:
a1 = x+y
print(a1)

tensor([[ 6.,  3.],
        [ 3.,  4.]])


In [102]:
a2 = t.add(x, y)
print(a2)

tensor([[ 6.,  3.],
        [ 3.,  4.]])


In [103]:
a3 = x.add(y)
print(a3)

tensor([[ 6.,  3.],
        [ 3.,  4.]])


In [104]:
a4 = t.empty(2, 2)
t.add(x, y, out=a4)
print(a4)

tensor([[ 6.,  3.],
        [ 3.,  4.]])


In [105]:
print(x.dtype)

torch.float32


Inplace add "tensor.add_(tensor2)"

In [106]:
a5 = x.add_(y)
print(a5)
print(x) # change the value of x

tensor([[ 6.,  3.],
        [ 3.,  4.]])
tensor([[ 6.,  3.],
        [ 3.,  4.]])


## Numpy bridge

In [173]:
a = t.ones(5)
print(a, type(a))

tensor([ 1.,  1.,  1.,  1.,  1.]) <class 'torch.Tensor'>


In [174]:
b = a.numpy()
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


Changing "a" will change "b". They share the same memory locations.

Only works for **in-place** operations.

In [187]:
a = t.ones(5)
b = a.numpy()
a.add_(1) # torch in-place operation
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [188]:
a = np.ones(5)
b = t.from_numpy(a)
np.add(a, 1, out=a) # numpy inplace operation
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [189]:
a = np.ones(5)
b = t.from_numpy(a)
a[0] += 1 # inplace operation
print(a)
print(b)

[2. 1. 1. 1. 1.]
tensor([ 2.,  1.,  1.,  1.,  1.], dtype=torch.float64)


No effect on the torch tensor, because this is not an in-place operation.

In [190]:
a = np.ones(5)
b = t.from_numpy(a)
a = np.add(a, 1) # numpy inplace operation
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


## Torch autograd

### Default: not require gradient

In [227]:
x = t.tensor([1,2,3])
print(x.requires_grad)

False


In [228]:
y = x+3
print(y.requires_grad)

False


### Calculate gradient (backward)

#### Example1

In [233]:
x = t.ones(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
True


In [234]:
y = x+2
print(y)
print(y.requires_grad)

tensor([[ 3.,  3.],
        [ 3.,  3.]])
True


In [235]:
y[0,0].backward()

In [236]:
x.grad

tensor([[ 1.,  0.],
        [ 0.,  0.]])

#### Example2

$y_i = (x_i+2)x_i^2$

$z = \frac{1}{4}\sum y_i$

$\frac{\partial z}{\partial x_i}=\frac{\partial z}{\partial y_i}\frac{\partial y_i}{\partial x_i}$

$\frac{\partial z}{\partial x_i}|_{x_i=1}=\frac{1}{4} \times 7 = 1.75$

In [242]:
x = t.ones(2, 2, requires_grad=True)
y = (x+2)*x**2
z = y.mean()
print(z)

tensor(3.)


In [243]:
z.backward()

In [244]:
x.grad

tensor([[ 1.7500,  1.7500],
        [ 1.7500,  1.7500]])