In [13]:
import numpy as np
print(np.__version__)

1.14.2


# numpy axis 
## Rank 2 array
### The first index is axis 0 (row)

In [30]:
a = np.array(range(0,9)).reshape(3,3)
print('Array a:\n', a)
print('Index 0 of axis 0:', a[0])
print('Index 1 of axis 0:', a[1])
print('Index 2 of axis 0:', a[2])
print('Sum along axis 0 (row):', np.sum(a, axis=0))

Array a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Index 0 of axis 0: [0 1 2]
Index 1 of axis 0: [3 4 5]
Index 2 of axis 0: [6 7 8]
Sum along axis 0 (row): [ 9 12 15]


### The second index is axis 1 (column)

In [32]:
a = np.array(range(0,9)).reshape(3,3)
print('Array a:\n', a)
print('Index 0 of axis 1:', a[:,0])
print('Index 1 of axis 1:', a[:,1])
print('Index 2 of axis 1:', a[:,2])
print('Sum along axis 1 (column):', np.sum(a, axis=1))

Array a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Index 0 of axis 1: [0 3 6]
Index 1 of axis 1: [1 4 7]
Index 2 of axis 1: [2 5 8]
Sum along axis 1 (column): [ 3 12 21]


## Rank 3 array
Rank 3 array's axis definition is very similar to rank 2 array.

The most outer square brackets represents axis 0.

The most inner square brackets represents axis 2.

In [20]:
b = np.array(range(0,8)).reshape(2,2,2)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [28]:
print('Index 0 of axis 0:\n', b[0])
print('Index 1 of axis 0:\n', b[1])
print('Sum along axis 0:\n', np.sum(b, axis=0))

Index 0 of axis 0:
 [[0 1]
 [2 3]]
Index 1 of axis 0:
 [[4 5]
 [6 7]]
Sum along axis 0:
 [[ 4  6]
 [ 8 10]]


In [33]:
print('Index 0 of axis 1:\n', b[:,0,:])
print('Index 1 of axis 1:\n', b[:,1,:])
print('Sum along axis 1:\n', np.sum(b, axis=1))

Index 0 of axis 1:
 [[0 1]
 [4 5]]
Index 1 of axis 1:
 [[2 3]
 [6 7]]
Sum along axis 1:
 [[ 2  4]
 [10 12]]


In [34]:
print('Index 0 of axis 2:\n', b[:,:,0])
print('Index 1 of axis 2:\n', b[:,:,1])
print('Sum along axis 2:\n', np.sum(b, axis=2))

Index 0 of axis 2:
 [[0 2]
 [4 6]]
Index 1 of axis 2:
 [[1 3]
 [5 7]]
Sum along axis 2:
 [[ 1  5]
 [ 9 13]]


# np.concatenate
a is 3\*3 array. b is 1\*3 array.

c = np.concatenate([a,b], axis=0) 

c is 4\*3 array (3+1)\*3.

In [12]:
a = np.zeros([3,3])
b = np.ones([1,3])
c = np.concatenate([a,b], axis=0)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]]


In [35]:
a = np.zeros([3,3])
b = np.ones([3,5])
c = np.concatenate([a,b], axis=1)
print(c)

[[0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]]


# np.append

In [40]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a = np.zeros([3,3])
b = np.ones([3,5])
c = np.append(a, b, axis=1)
print(c)

[[0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]]


# np.stack

# np.hstack

# np.vstack